services:
  mossy-password:
    image: 'ghcr.io/day-fit/mossy-password:latest'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6797/actuator/health"]
      retries: 3
      timeout: 5s
      interval: 10s
    depends_on:
      - 'postgres'
    ports:
      - '8080:8080'
    environment:
      - 'SPRING_PROFILES_ACTIVE=prod'
      - 'DB_NAME=${DB_NAME}'
      - 'DB_NAME=${DB_NAME}'
      - 'DB_USER=${DB_USER}'
      - 'DB_PASSWORD=${DB_PASSWORD}'
      - 'MOSSY_STOMP_HOST=wss://mossy.dayfit.pl'
    profiles:
      - !dev
  mossy-device:
    image: 'ghcr.io/day-fit/mossy-password:latest'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6797/actuator/health" ]
      retries: 3
      timeout: 5s
      interval: 10s
    depends_on:
      - 'postgres'
    ports:
      - '8081:8081'
    environment:
      - 'SPRING_PROFILES_ACTIVE=prod'
      - 'DB_NAME=${DB_NAME}'
      - 'DB_USER=${DB_USER}'
      - 'DB_PASSWORD=${DB_PASSWORD}'
      - 'MOSSY_STOMP_HOST=wss://mossy.dayfit.pl'
    profiles:
      - !dev

  postgres:
    image: 'postgres:18.1-alpine'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USER}'
    volumes:
      - 'postgres:/var/lib/postgresql'
    ports:
      - '5432:5432'
volumes:
  postgres: