services:
  mossy:
    image: 'ghcr.io/day-fit/mossy-core:latest'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6797/actuator/health"]
      retries: 3
      timeout: 5s
      interval: 10s
    depends_on:
      - 'postgres'
    ports:
      - '6797:6797'
    environment:
      - 'SPRING_PROFILES_ACTIVE=prod'
      - 'DB_NAME=mossy_vault'
      - 'DB_USER=${DB_USER}'
      - 'DB_PASSWORD=${DB_PASSWORD}'
      - 'MOSSY_STOMP_HOST=wss://mossy.dayfit.pl'
    profiles:
      - !dev

  postgres:
    image: 'postgres:18.1-alpine'
    environment:
      - 'POSTGRES_DB=mossy_vault'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USER}'
    volumes:
      - 'postgres:/var/lib/postgresql'
    ports:
      - '5432:5432'
volumes:
  postgres: